import Head from "next/head";
import styles from "../styles/Home.module.css";



export default function Home() {


  return (
    <div className={styles.container}>

      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="blog, netxjs blog , blog for coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>Welcome to My Blog!</h1>
        <div className={styles.imgwarp}>
        {/* <Image className={styles.myimg} src="/home.webp" alt="img" width={257} height={150}></Image> */}
        <img className={styles.myimg} src="/home.webp" alt="img" width={257} height={150} />
        </div>

        <p className={styles.description}>A Blog For Coder By A Coder ! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Excepturi a tenetur, soluta exercitationem doloribus iure facilis deleniti natus, recusandae quos inventore est eligendi nam reiciendis, vitae architecto dolorum ipsum magni.</p>

        <div className={styles.container}>
          <h2 className={styles.latest}>LATEST BLOG POST</h2>

          <div className={styles.blogItem}>
            <h3>How to learn javaScript in 2022</h3>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta
              tempore aspernatur iure iusto reprehenderit earum reiciendis
              dignissimos sapiente at quia expedita eum hic impedit dolore
              tenetur aut, delectus, fuga tempora? Lorem ipsum dolor sit, amet

            </p>
            <button className={styles.btn}>read more</button>
          </div>

          <div className={styles.blogItem}>
            <h3>How to learn javaScript in 2022</h3>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta
              tempore aspernatur iure iusto reprehenderit earum reiciendis
              dignissimos sapiente at quia expedita eum hic impedit dolore
              tenetur aut, delectus, fuga tempora? Lorem ipsum dolor sit, amet
  
            </p>
            <button className={styles.btn}>read more</button>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn javaScript in 2022</h3>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta
              tempore aspernatur iure iusto reprehenderit earum reiciendis
              dignissimos sapiente at quia expedita eum hic impedit dolore
              tenetur aut, delectus, fuga tempora? Lorem ipsum dolor sit, amet
            </p>
            <button className={styles.btn}>read more</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>OWN BY DEEPAK VIKRANT</p>
      </footer>
    </div>
  );
}
