import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Script from "next/script";
import Link from "next/link";
import Dummy from "../components/dummy";

export default function Home() {


  return (
    <div className={styles.container}>

      <style jsx>
        {`
        .myspan{
          color :red;
        }
        `}
      </style>

      <Dummy/>


      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="blog, netxjs blog , blog for coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="/sc.js" strategy="lazyOnload"></Script>
      <nav className={styles.mainnav}>
        <ul>
          <Link href='/home'><a><li>Home</li></a></Link>
          <Link href='/about'><a><li>About</li></a></Link>
          <Link href='/blog'><a><li>Blog</li></a></Link>
          <Link href='/contact'><a><li>Contact</li></a></Link>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to My Blog!</h1>

        <p className={styles.description}>A Blog For Coder By A Coder !</p>

        <div className="blogs">
          <span className="myspan"> <h2>POPULAR BLOG POST</h2> </span>

          <div className="blogItem">
            <h3 className="Dummy">How to learn javaScript in 2022</h3>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta
              tempore aspernatur iure iusto reprehenderit earum reiciendis
              dignissimos sapiente at quia expedita eum hic impedit dolore
              tenetur aut, delectus, fuga tempora? Lorem ipsum dolor sit, amet
              consectetur adipisicing elit. Iste deserunt neque aliquam qui
              libero, quis doloremque suscipit impedit a minus incidunt quisquam
              eaque tenetur quas at exercitationem laboriosam nam. Natus.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn javaScript in 2022</h3>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta
              tempore aspernatur iure iusto reprehenderit earum reiciendis
              dignissimos sapiente at quia expedita eum hic impedit dolore
              tenetur aut, delectus, fuga tempora? Lorem ipsum dolor sit, amet
              consectetur adipisicing elit. Iste deserunt neque aliquam qui
              libero, quis doloremque suscipit impedit a minus incidunt quisquam
              eaque tenetur quas at exercitationem laboriosam nam. Natus.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn javaScript in 2022</h3>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta
              tempore aspernatur iure iusto reprehenderit earum reiciendis
              dignissimos sapiente at quia expedita eum hic impedit dolore
              tenetur aut, delectus, fuga tempora? Lorem ipsum dolor sit, amet
              consectetur adipisicing elit. Iste deserunt neque aliquam qui
              libero, quis doloremque suscipit impedit a minus incidunt quisquam
              eaque tenetur quas at exercitationem laboriosam nam. Natus.
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
